const services = [
  {
    id: 1,
    course: "Angular",
    discription: "Angular - the complete guide for beginner",
    price: "$100",
    img: "./image/angular.jpg",
    lavel: "Advance",
  },
  {
    id: 2,
    course: "Laravel",
    discription: "Laravel: The Ultimate Beginner’s Guide to Learn",
    price: "$90",
    img: "./image/laravel.jpg",
    lavel: "Intermediate",
  },
  {
    id: 3,
    course: "Gatsby",
    discription: "Revolutionize how you build the web",
    price: "$130",
    img: "./image/gatsby.jpg",
    lavel: "Advance",
  },
  {
    id: 4,
    course: "Graph QL",
    discription: "GraphQL: introduction to graphQL for beginners",
    price: "$150",
    img: "./image/graph_Ql.jpg",
    lavel: "Intermediate",
  },
  {
    id: 5,
    course: "Javascript",
    discription: "Applying JavaScript and using the console.",
    price: "$200",
    img: "./image/Javascript.jpg",
    lavel: "Beginner",
  },
  {
    id: 6,
    course: "Node js",
    discription: "Beginning Node.js, Express & MongoDB Development",
    price: "$140",
    img: "./image/node_js.jpg",
    lavel: "Beginner",
  },
  {
    id: 7,
    course: "Python",
    discription: "The Python Course: build web application",
    price: "$220",
    img: "./image/python.jpg",
    lavel: "Intermediate",
  },
  {
    id: 8,
    course: "React",
    discription: "How to easily create a website with React",
    price: "$150",
    img: "./image/react.jpg",
    lavel: "Beginner",
  },
];
export { services };
